export const phoneVerfication = {
  VERIFY_PHONE: 'VERIFY_PHONE',
  VERIFY_CODE: 'VERIFY_CODE',
  USER_DATA: 'USER_AUTH_INFO',
  ACCOUNT_DATA: 'ACCOUNT_DATA',
  UPDATE_BALANCE: 'UPDATE_BALANCE'
};


export const transferVarification = {
  RECEIVER_INFO: ' RECEIVER_INFO',
  DELETE_RECEIVER_INFO: ' DELETE_RECEIVER_INFO',
  SUBTRACT_BLANCE: 'SUBTRACT_BLANCE',
  BANK_STATEMENTS: 'BANK_STATEMENTS'
  
};
